package com.cultuzz.accounting.hbm.accounting;

// Generated Mar 15, 2016 11:56:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CultswitchNewTariff generated by hbm2java
 */
@Entity
@Table(name = "CULTSWITCH_NEW_TARIFF", catalog = "accounting", uniqueConstraints = @UniqueConstraint(columnNames = "CURRENCY"))
public class CultswitchNewTariff implements java.io.Serializable {

	private Integer id;
	private String currency;
	private float commission;
	private Date endDate;
	private float minimumValue;
	private float maximumValue;
	private int creatorUserId;
	private Date lastUpdated;

	public CultswitchNewTariff() {
	}

	public CultswitchNewTariff(String currency, float commission, Date endDate,
			float minimumValue, float maximumValue, int creatorUserId,
			Date lastUpdated) {
		this.currency = currency;
		this.commission = commission;
		this.endDate = endDate;
		this.minimumValue = minimumValue;
		this.maximumValue = maximumValue;
		this.creatorUserId = creatorUserId;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CURRENCY", unique = true, nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "COMMISSION", nullable = false, precision = 8)
	public float getCommission() {
		return this.commission;
	}

	public void setCommission(float commission) {
		this.commission = commission;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "MINIMUM_VALUE", nullable = false, precision = 8)
	public float getMinimumValue() {
		return this.minimumValue;
	}

	public void setMinimumValue(float minimumValue) {
		this.minimumValue = minimumValue;
	}

	@Column(name = "MAXIMUM_VALUE", nullable = false, precision = 8)
	public float getMaximumValue() {
		return this.maximumValue;
	}

	public void setMaximumValue(float maximumValue) {
		this.maximumValue = maximumValue;
	}

	@Column(name = "CREATOR_USER_ID", nullable = false)
	public int getCreatorUserId() {
		return this.creatorUserId;
	}

	public void setCreatorUserId(int creatorUserId) {
		this.creatorUserId = creatorUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
