package com.cultuzz.accounting.hbm.accounting;

// Generated Mar 15, 2016 11:56:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "CURRENCY", catalog = "accounting")
public class Currency implements java.io.Serializable {

	private Short id;
	private String name;
	private String shortName;
	private String symbol;
	private Date lastUpdated;

	public Currency() {
	}

	public Currency(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Currency(String name, String shortName, String symbol,
			Date lastUpdated) {
		this.name = name;
		this.shortName = shortName;
		this.symbol = symbol;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SHORT_NAME", length = 3)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "SYMBOL", length = 10)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
