package com.cultuzz.accounting.hbm.accounting;

// Generated Mar 15, 2016 11:56:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObjectNewCommissionStatus generated by hbm2java
 */
@Entity
@Table(name = "OBJECT_NEW_COMMISSION_STATUS", catalog = "accounting")
public class ObjectNewCommissionStatus implements java.io.Serializable {

	private int objectId;
	private boolean newCommissionStatus;
	private Date effectiveDate;
	private int assignedUserId;
	private Date lastUpdated;

	public ObjectNewCommissionStatus() {
	}

	public ObjectNewCommissionStatus(int objectId, boolean newCommissionStatus,
			Date effectiveDate, int assignedUserId, Date lastUpdated) {
		this.objectId = objectId;
		this.newCommissionStatus = newCommissionStatus;
		this.effectiveDate = effectiveDate;
		this.assignedUserId = assignedUserId;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@Column(name = "OBJECT_ID", unique = true, nullable = false)
	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	@Column(name = "NEW_COMMISSION_STATUS", nullable = false)
	public boolean isNewCommissionStatus() {
		return this.newCommissionStatus;
	}

	public void setNewCommissionStatus(boolean newCommissionStatus) {
		this.newCommissionStatus = newCommissionStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EFFECTIVE_DATE", nullable = false, length = 10)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "ASSIGNED_USER_ID", nullable = false)
	public int getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(int assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
